package shopify

import "time"

// TransactionRepository manages order transactions
type TransactionRepository interface {
	// List retrieves all order transactions by order ID.
	List(orderID int64) (Transactions, error)
	// Get retrieves an order transaction by its IDs.
	Get(orderID int64, id int64) (Transaction, error)
}

type Transactions []Transaction

type ExtendedAuthorizationAttributes struct {
	// The date and time (ISO 8601 format) when the standard authorization period expires. After expiry, an extended authorization fee is applied upon capturing the payment.
	StandardAuthorizationExpiresAt time.Time
	// The date and time (ISO 8601 format) when the extended authorization period expires. After expiry, the merchant can't capture the payment.
	ExtendedAuthorizationExpiresAt time.Time
}

type Location struct {
	ID int64
}

type PaymentDetails struct {
	// The issuer identification number (IIN), formerly known as bank identification number (BIN) of the customer's credit card. This is made up of the first few digits of the credit card number.
	CreditCardBin string
	// The response code from the address verification system. The code is always a single letter.
	AvsResultCode string
	// The response code from the credit card company indicating whether the customer entered the card security code, or card verification value, correctly. The code is a single letter or empty string.
	CvvResultCode string
	// The customer's credit card number, with most of the leading digits redacted.
	CreditCardNumber string
	// The name of the company that issued the customer's credit card.
	CreditCardCompany string
	// The holder of the credit card.
	CreditCardName string
	// The wallet type where this credit card was retrieved from.
	CreditCardWallet string
	// The month in which the credit card expires.
	CreditCardExpirationMonth int64
	// The year in which the credit card expires.
	CreditCardExpirationYear int64
	// Details for payment methods that require additional buyer action to complete the order transaction.
	BuyerActionInfo interface{}
	// The name of the payment method used by the buyer to complete the order transaction.
	PaymentMethodName string
}

type PaymentsRefundAttributes struct {
	// The current status of the refund
	Status string
	// A unique number associated with the transaction that can be used to track the refund. This property has a value only for transactions completed with Visa or Mastercard
	AcquirerReferenceNumber string
}

type CurrencyExchangeAdjustment struct {
	// The ID of the adjustment.
	ID int64
	// The difference between the amounts on the associated transaction and the parent transaction.
	Adjustment string
	// The amount of the parent transaction in the shop currency.
	OriginalAmount string
	// The amount of the associated transaction in the shop currency.
	FinalAmount string
	// The shop currency.
	Currency string
}

// Transaction the transaction of an order
type Transaction struct {
	// The amount of money included in the transaction.
	Amount string
	// The authorization code associated with the transaction.
	Authorization string
	// The date and time (ISO 8601 format) when the Shopify Payments authorization expires.
	AuthorizationExpiresAt time.Time
	// The date and time (ISO 8601 format) when the transaction was created.
	CreatedAt time.Time
	// The three-letter code (ISO 4217 format) for the currency used for the payment.
	Currency string
	// The ID for the device.
	DeviceID int64
	// A standardized error code, independent of the payment provider.
	ErrorCode string
	// The attributes associated with a Shopify Payments extended authorization period
	ExtendedAuthorizationAttributes ExtendedAuthorizationAttributes
	// The name of the gateway the transaction was issued through.
	Gateway string
	// The ID of the transaction
	ID int64
	// The transaction's type.
	Kind string
	// The ID of the physical location where the transaction was processed.
	Location Location
	// A string generated by the payment provider with additional information about why the transaction succeeded or failed.
	Message string
	// The ID for the order that the transaction is associated with.
	OrderID int64
	// Information about the payment method used for this transaction
	PaymentDetails PaymentDetails
	// The ID of an associated transaction.
	ParentID int64
	// The attributes associated with a Shopify Payments refund
	PaymentsRefundAttributes PaymentsRefundAttributes
	// The date and time (ISO 8601 format) when a transaction was processed. This value is the date that's used in the analytic reports. By default, it matches the created_at value.
	ProcessedAt time.Time
	// A transaction receipt attached to the transaction by the gateway. The value of this field depends on which gateway the shop is using.
	Receipt interface{}
	// The origin of the transaction. This is set by Shopify and can't be overridden.
	SourceName string
	// The status of the transaction. Valid values: pending, failure, success, and error.
	Status string
	// Specifies the available amount with currency to capture on the gateway in shop and presentment currencies. Only available when an amount is capturable or manually mark as paid.
	TotalUnsettledSet interface{}
	// Whether the transaction is a test transaction.
	Test bool
	// The ID for the user who was logged into the Shopify POS device when the order was processed, if applicable.
	UserID int64
	// An adjustment on the transaction showing the amount lost or gained due to fluctuations in the currency exchange rate.
	CurrencyExchangeAdjustment CurrencyExchangeAdjustment
}
