on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
        matrix:
          go-version: [1.21.x]
          os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Vet
      run: go vet ./...
    - name: Test
      run: go test ./...